version: '3.4'

# This Guideline will show you how to config env
# https://medium.com/better-programming/using-variables-in-docker-compose-265a604c2006

services:
  app:
    image: creka-image
    build:
      context: .
      target: production
    env_file: .env
    environment:
      APP_PORT: $APP_PORT
      NODE_ENV: $NODE_ENV
      RDS_USERNAME: $RDS_USERNAME
      RDS_PASSWORD: $RDS_PASSWORD
      RDS_DATABASE: $RDS_DATABASE
      RDS_HOST: $RDS_HOST
    ports:
      - 3000:$APP_PORT
    volumes:
      - prod_dep:/prod_dep/node_modules
      - dev_dep:/builder/app/node_modules
      - yarn_cache:/usr/local/share/.cache/yarn
    command: yarn run start
    networks:
      - nw_template_rest
    depends_on:
      - db
    # - nginx
    # - redis

  db:
    build: ./docker/mysql/
    image: mysql-image-1
    container_name: db-graphql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $RDS_DATABASE
      MYSQL_USER: $RDS_USERNAME
      MYSQL_PASSWORD: $RDS_PASSWORD
    ports:
      - 3306:$MYSQL_PORT
    networks:
      - nw_template_rest
    # volumes:
    #   - ./mysql:/var/lib/mysql
networks:
  nw_template_rest:
    driver: bridge

volumes:
  yarn_cache:
  dev_dep:
  prod_dep:
